---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install rubygems
  - gem install bundler
  - bundle install

install:
  # Install Ansible.
  - pip install ansible==1.5.0

script:
  - "rake travis"
