---
boxes:
  - name: precise
    box: ubuntu/precise64
    ip: 192.168.59.4
    scenarios:
      - default
      - ssl
  - name: trusty
    box: ubuntu/trusty64
    ip: 192.168.59.5
    scenarios:
      - default
      - ssl

scenarios:
  default: {}
  ssl:
    registry_port: 443
    registry_ssl: true
