---
- name: install nginx server
  apt: name=nginx-extras state=present

- name: install nginx vhost
  template: >
    src=nginx.j2
    dest=/etc/nginx/sites-enabled/docker-registry
  notify: restart nginx

- name: remove default nginx vhost
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: domain == 'localhost'
  notify: restart nginx

- name: ensure nginx is running
  service: name=nginx state=running enabled=yes

